// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkm4UhDBeOyX5EiPrTu4yd_OqRNGPkSac',
    appId: '1:1043384905386:web:edc391b0bcd1db49832ad3',
    messagingSenderId: '1043384905386',
    projectId: 'edu-vista-8e703',
    authDomain: 'edu-vista-8e703.firebaseapp.com',
    storageBucket: 'edu-vista-8e703.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsANFoghFh3yJJMI12GzfBduZYrFfP8R8',
    appId: '1:1043384905386:android:bcde579cfafe8339832ad3',
    messagingSenderId: '1043384905386',
    projectId: 'edu-vista-8e703',
    storageBucket: 'edu-vista-8e703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvVTLnf--6-IwbqffbYBatgxEIOutEQU',
    appId: '1:1043384905386:ios:ac9225bf6fdabea7832ad3',
    messagingSenderId: '1043384905386',
    projectId: 'edu-vista-8e703',
    storageBucket: 'edu-vista-8e703.appspot.com',
    iosBundleId: 'com.example.task11Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkvVTLnf--6-IwbqffbYBatgxEIOutEQU',
    appId: '1:1043384905386:ios:ac9225bf6fdabea7832ad3',
    messagingSenderId: '1043384905386',
    projectId: 'edu-vista-8e703',
    storageBucket: 'edu-vista-8e703.appspot.com',
    iosBundleId: 'com.example.task11Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkm4UhDBeOyX5EiPrTu4yd_OqRNGPkSac',
    appId: '1:1043384905386:web:eb6542bf493f66d8832ad3',
    messagingSenderId: '1043384905386',
    projectId: 'edu-vista-8e703',
    authDomain: 'edu-vista-8e703.firebaseapp.com',
    storageBucket: 'edu-vista-8e703.appspot.com',
  );

}